version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-buster

    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

    working_directory: ~/selenium-project

    steps:
      - checkout

      # Set up the project dependencies
      - run:
          name: Set up project dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y maven

      # Run the Selenium script
      - run:
          name: Run Selenium script
          command: |
            mvn test

workflows:
  version: 2
  build:
    jobs:
      - build
